# -*- coding: utf-8 -*-
"""NN_DataCleaner/Demographics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJtXoJtJIpMxXGTkqlxv4jhqfGVq4Q8f
"""

#imports
import numpy as np
import pandas as pd
from google.colab import files

#upload files
files.upload()

#Get demographics section into more readable format
demosdf = pd.read_excel('1.1_demographics_raw_Spring2024.xlsx')
filtered_demos = demosdf[['subject', 'trialcode', 'response']].copy()
filtered_demos = filtered_demos.sort_values(by=['subject', 'trialcode'])
demos_pivot = filtered_demos.pivot(index = 'subject', columns='trialcode', values='response')
demos_pivot

# Getting Demographic Information
for column in demos_pivot.columns:
    if demos_pivot[column].dtype == 'object':
        value_counts = demos_pivot[column].value_counts()
        print(value_counts)
        print()

#getting social participation index data cleaned
spi = pd.read_excel('1.1_outgoingscale_cleaned_Spring2024.xlsx')
spi_df = spi[['subject', 'sum']].copy()
spi_df = spi_df.rename(columns={'subject': 'subject', 'sum': 'spi'})
spi_df

#getting rosenberg self esteem data cleaned
rse = pd.read_excel('1.1_rse_summary_Spring2024.xlsx')
rse_df = rse[['subjectid', 'rosenbergscore']].copy()
rse_df = rse_df.rename(columns={'subjectid': 'subject', 'rosenbergscore': 'rse'})
rse_df

#merging dataframes
merged_df = pd.merge(demos_pivot, spi_df, on='subject', how='inner')
final_df = pd.merge(merged_df, rse_df, on='subject', how='inner')
final_df

#downloading dataframe
final_df.to_excel('cleanInquisitData.xlsx')
files.download('cleanInquisitData.xlsx')